### ISSUE TITLE
X-Frame-Options Header Not Set.

### ISSUE THREAD

**Issue by Aholicknight** [CompCamps/WebsiteArchive#12]
X-Frame-Options header is not included in the HTTP response to protect against 'ClickJacking' attacks. 

Site effected: [www.compcamps.com](http://www.compcamps.com)

Most modern Web browsers support the X-Frame-Options HTTP header. Ensure it's set on all web pages returned by your site (if you expect the page to be framed only by pages on your server (e.g. it's part of a FRAMESET) then you'll want to use SAMEORIGIN, otherwise if you never expect the page to be framed, you should use DENY. ALLOW-FROM allows specific websites to frame the web page in supported web browsers).

**Comment by BrettMayson** [comment]
This repository is not for www.compcamps.com at the moment. This is a development repository.

**Comment by Aholicknight** [comment]
@BmanDesignsCanada Sorry about that. I noticed that you have a project on this for ¨SQL Injection¨ If you want. I can find vulnerability and report them to you. I am asking you in advanced beacause if I did it without you knowing/asking it would be illegal.

**Comment by BrettMayson** [comment]
Maybe in the future, but not at the moment. If you look in the code and find any mistakes of vulnerabilities that's cool, but we're not ready for any pentesting at the moment.

**Comment by Aholicknight** [comment]
@BmanDesignsCanada Alright.

**Comment by BrettMayson** [comment]
This has yet to be fixed in master
