### ISSUE TITLE
POP3s and imaps vulnerable by Weak Diffie-Hellman.

### ISSUE THREAD

**Issue by Aholicknight** [CompCamps/WebsiteArchive#18]
Transport Layer Security (TLS) services that use Diffie-Hellman groups of insufficient strength, especially those using one of a few commonly shared groups, may be susceptible to passive eavesdropping attacks.

Nmap scan:

`995/tcp  open   pop3s`
`| ssl-dh-params:`
`|   VULNERABLE:`
`|   Diffie-Hellman Key Exchange Insufficient Group Strength`
`|     State: VULNERABLE`

`993/tcp  open   imaps`
`| ssl-dh-params:`
`|   VULNERABLE:`
`|   Diffie-Hellman Key Exchange Insufficient Group Strength`
`|     State: VULNERABLE`

**Comment by BrettMayson** [comment]
We don't use POP3S or IMAPS. This is not something we can do anything about nor would we need to.

**Comment by Aholicknight** [comment]
@brettmayson Alright.

**Comment by Aholicknight** [comment]
@brettmayson Not trying to argue but if we dont use them then why are those ports open on [www.compcamps.com](http://www.compcamps.com)?

**Comment by BrettMayson** [comment]
Our hosting provider has a mail server running, but it is unused
