### ISSUE TITLE
Remove library duplication between core and dash.

### ISSUE THREAD

**Issue by rye761** [CompCamps/WebsiteArchive#2]
Font-awesome is double included for sure, not sure if jQuery is also.

**Comment by BrettMayson** [comment]
I wanted to do this but wasn't sure how you were going to setup the homepage. Ideally, we should use a CDN for as many libraries as possible.

**Comment by rye761** [comment]
Oh okay. I didn't realize that you wanted to use CDN. We can used CDN for font-awesome then and that would solve the issue.

**Comment by BrettMayson** [comment]
Just fewer files for us to worry about and faster loading.

**Comment by rye761** [comment]
Sounds good.

**Comment by BrettMayson** [comment]
I'm pretty sure this is mostly handled, I don't think this issue needs to be open anymore.
