### ISSUE TITLE
Cant signup

### ISSUE THREAD

**Issue by Aholicknight** [CompCamps/WebsiteArchive#26]
I have everything valid for the registration but when I click next it wont proceed.

**Comment by Aholicknight** [comment]
Nevermind, I was using a browser that dident work with the signup page.

**Comment by BrettMayson** [comment]
What browser were you using?

**Comment by Aholicknight** [comment]
@brettmayson Internet Explorer (**yes i know**), Also my parents wrote an email to your support email `computercamps@gmail.com` about a issue with payment. Please look at it, thanks.
