### ISSUE TITLE
Image Slider Loading Time

### ISSUE THREAD

**Issue by BrettMayson** [CompCamps/WebsiteArchive#3]
The google photos slider takes a noticeable amount of time to load. I would like to find a better way to generate the list of images on the fly with Javascript. This isn't a huge issue though and I don't want to over complicate it.

**Comment by Aholicknight** [comment]
Are the images bigger then 10 mb?

**Comment by BrettMayson** [comment]
The images themselves are rarely larger than 1MB. What takes time is the script that gets the list of image URLs from Google Photos.

**Comment by BrettMayson** [comment]
aac592e brought in image preloading. The slider seems to be working better in general now.

**Comment by Aholicknight** [comment]
Great.

**Comment by BrettMayson** [comment]
Images load fast enough on the live site, closing.
