### ISSUE TITLE
Payment portal is through HTTP.

### ISSUE THREAD

**Issue by Aholicknight** [CompCamps/WebsiteArchive#47]
This problem should be big because let's say you are making a payment on a open wifi such as a cafe, public place, hotel, etc. If anyone is doing a MITM attack they will be able to see the credit card info being sent thru. 

Link: [http://compcamps.com/dash/register](http://compcamps.com/dash/register)
![image](https://user-images.githubusercontent.com/7843719/41504278-52d2f3de-71a7-11e8-911c-0fa44b2f6ef4.png)

**Comment by BrettMayson** [comment]
Our website is currently http only as our certificates expired, an issue we are working to fix. All credit card info is sent through https to Stripe and is never sent unencrypted. I am closing this in favour of #11
