### ISSUE TITLE
Wrong PHP versions on Trusty

### ISSUE THREAD

**Issue by BrettMayson** [CompCamps/WebsiteArchive#6]
e4736338425fb2aabd3da22d2f91cd4731ad16fb has caused the PHP setup in Vagrant to be using different versions and the setup is not done correctly. We'll need to use Xenial. The dash branch is still on Xenial, master is on Trusty.

**Comment by rye761** [comment]
Looks like you reverted to xenial on the master branch which is all good with me, so I'm closing this.
